services:
  - type: web
    name: cookie-api
    runtime: docker
    plan: free
    autoDeploy: true

    envVars:
      - key: TARGET_URL
        value: https://5afterdark.mom/video/7e4de128-b10f-dc2b-0542-7590c441630e
